"""add stripe_webhook_events ledger

Revision ID: ceb25f41fbf2
Revises: e42bdc93fd06
Create Date: 2026-07-15 14:57:54.942044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ceb25f41fbf2"
down_revision: str | None = "e42bdc93fd06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stripe_webhook_events_event_id"), "stripe_webhook_events", ["event_id"], unique=True)
    op.create_index(op.f("ix_stripe_webhook_events_id"), "stripe_webhook_events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stripe_webhook_events_id"), table_name="stripe_webhook_events")
    op.drop_index(op.f("ix_stripe_webhook_events_event_id"), table_name="stripe_webhook_events")
    op.drop_table("stripe_webhook_events")
    # ### end Alembic commands ###
